### ISSUE TITLE
Overwriting click listeners when adding GeoJsonLayers

### ISSUE THREAD

**Issue by meierjan** [SupasinTatiyanupanwong/map-kit-android-utils#1]
Hey @SupasinTatiyanupanwong , 

this is an impressive library that you wrote! Thanks a ton. I am currently implementing `MapView` support myself for the core part and it worked pretty well - so thanks for saving me a lot of work by providing me a basis.

However, when I tested the app after using this set of libraries everything seemed to work fine. After a while I faced an issue that my `onMapMarkerClicked`-Listener was removed. I debugged it and I found out that for some reason you are resetting all listeners for the `MapManager` whenever a new Layer ist added.

This is pretty different from the original utils behavior, isn't it?

What do you suggest to mitigate this behavior?

https://github.com/SupasinTatiyanupanwong/map-kit-android-utils/blob/fb76c2c18fd87210c74ed8928a8ead4646340199/maps-utils/src/main/java/me/tatiyanupanwong/supasin/android/libraries/kits/maps/utils/collections/MarkerManager.java#L52

**Comment by SupasinTatiyanupanwong** [comment]
Hi @meierjan !

Thank you for using my set of libraries, it is my pleasure.

This utility library is technically a fork of the original  one, so its behaviour is expected to be the same.

Whenever you use object managers, i.e. `MarkerManager`, you will need to set listener through its collections instead of map directly.
https://github.com/SupasinTatiyanupanwong/map-kit-android-utils/blob/fb76c2c18fd87210c74ed8928a8ead4646340199/maps-utils/src/main/java/me/tatiyanupanwong/supasin/android/libraries/kits/maps/utils/collections/MarkerManager.java#L192

If you have multiple layers, you will need to have a shared object managers so that they won't interfere with one another.
https://github.com/SupasinTatiyanupanwong/map-kit-android-utils/blob/fb76c2c18fd87210c74ed8928a8ead4646340199/sample/src/main/java/me/tatiyanupanwong/supasin/android/samples/kits/maps/utils/MultiLayerDemoActivity.java#L67

If you found that the behaviour is different than the original, could you please provide me some sample so that I can check?

**Comment by meierjan** [comment]
Thanks for the heads-up. I guess I was just coming from an old version and I migrated accordingly. Thanks!
